### ISSUE TITLE
Add real musical instrument

### ISSUE THREAD

**Issue by surikov** [chrisguttandin/analog4all-client#363]
Add real musical instrument into project. See example of dynamic loading:

https://surikov.github.io/webaudiofont/examples/dynamic.html

- 1500 instruments (piano, guitar, horn etc. )
- 200 drums

**Comment by chrisguttandin** [comment]
Hi @surikov, thanks for your contribution.

I’m sorry to say that adding software instruments would subvert our goal to give people remote access to physical instruments. So I don’t think we are going to add WebAudioFonts.

Nevertheless, I think WebAudioFonts is definitely a cool project on its own.
